### ISSUE TITLE
CULA library not found 

### ISSUE THREAD

**Issue by AhmedShaban94** [martin-velas/SLAM_plus_plus#1]
Hi, 
I just want to ask is there any alternative to CULA library support as it's not freely available anymore  ? 
I want to use the GPU accelerated version of SLAM++ .

**Comment by martin-velas** [comment]
Sorry , but this is not official repo of SLAM++ (just my private copy for experiments) - go to the official website https://sourceforge.net/p/slam-plus-plus/wiki/Home/
